In [9]:
import pandas as pd 
import numpy as np
url = 'FOLK1A.csv'
df = pd.read_csv(url,sep=';')
df['TID'] = df['TID'].map(lambda x:x[:-2]) #cut the last 2 characters
df.to_csv('demografic_cleaned.csv',header=False, index=False)

In [11]:
cleaned_file = 'demografic_cleaned.csv'

In [15]:
loaded_data = np.loadtxt(cleaned_file, delimiter=',', dtype=np.uint)
print(loaded_data)

[[    0     1     0  2008 32976]
 [    0     1     0  2009 33656]
 [    0     1     0  2010 32435]
 ...
 [  751     2   100  2018    18]
 [  751     2   100  2019    21]
 [  751     2   100  2020    23]]


In [23]:
import csv
city_list = {}
city_file = '../../../../data/DKstat_bykoder.csv'
csv_data = csv.reader(open(city_file, encoding = 'utf-8'), delimiter = ';')
csv_data_list = list(csv_data)

for csv_data in csv_data_list:
    city_list[int(csv_data[0])] = csv_data[1]
    
city_list

{0: ' Hele-landet',
 84: ' Region-Hovedstaden',
 101: ' København',
 147: ' Frederiksberg',
 155: ' Dragør',
 185: ' Tårnby',
 165: ' Albertslund',
 151: ' Ballerup',
 153: ' Brøndby',
 157: ' Gentofte',
 159: ' Gladsaxe',
 161: ' Glostrup',
 163: ' Herlev',
 167: ' Hvidovre',
 169: ' Høje-Taastrup',
 183: ' Ishøj',
 173: ' Lyngby-Taarbæk',
 175: ' Rødovre',
 187: ' Vallensbæk',
 201: ' Allerød',
 240: ' Egedal',
 210: ' Fredensborg',
 250: ' Frederikssund',
 190: ' Furesø',
 270: ' Gribskov',
 260: ' Halsnæs',
 217: ' Helsingør',
 219: ' Hillerød',
 223: ' Hørsholm',
 230: ' Rudersdal',
 400: ' Bornholm',
 411: ' Christiansø',
 85: ' Region-Sjælland',
 253: ' Greve',
 259: ' Køge',
 350: ' Lejre',
 265: ' Roskilde',
 269: ' Solrød',
 320: ' Faxe',
 376: ' Guldborgsund',
 316: ' Holbæk',
 326: ' Kalundborg',
 360: ' Lolland',
 370: ' Næstved',
 306: ' Odsherred',
 329: ' Ringsted',
 330: ' Slagelse',
 340: ' Sorø',
 336: ' Stevns',
 390: ' Vordingborg',
 83: ' Region-Syddanmark',
 420:

In [28]:
def summed_by_city(city_code):
    print(city_code)
    
    ld = loaded_data
    control = ld[np.isin(ld[:,0],[city_code])]
    
    # male population 
    male = control[(control[:,3] == 2020) & (control[:,1] == 1)]
    male_population = male[:,4].sum()
    
    # female population
    female = control[(control[:,3] == 2020) & (control[:,1] == 2)]
    female_popultaion = female[:,4].sum()
    
    # population
    population =  control[(control[:,3] == 2020)]
    total_population = population[:,4].sum()
    
    # pct
    male_pct = (male_population/total_population) * 100
    female_pct = (female_popultaion/total_population) * 100
    
    
    print("Male population: {}, {:0.2f}%, female population: {}, {:0.2f}%, in area {} ".format(male_population, male_pct, female_popultaion, female_pct, city_code))
    
    if total_population == 0:
        return 0
    else:
        return male_pct

In [29]:
summed_by_city(751)

751
Male population: 170015, 49.13%, female population: 176057, 50.87%, in area 751 


49.127060264915976

In [36]:
def get_male_pct_and_city(city_list):
    
    male_pct_and_city = {}
    
    for city_code, city_name in city_list.items():
        male_pct_and_city[city_name] = summed_by_city(city_code)
        
    return male_pct_and_city

In [37]:
male_pct_dict = get_male_pct_and_city(city_list)

0
Male population: 2864155, 49.75%, female population: 2893016, 50.25%, in area 0 
84
Male population: 894698, 49.08%, female population: 928125, 50.92%, in area 84 
101
Male population: 0, nan%, female population: 0, nan%, in area 101 
147
Male population: 48816, 47.43%, female population: 54109, 52.57%, in area 147 
155
Male population: 0, nan%, female population: 0, nan%, in area 155 
185
Male population: 0, nan%, female population: 0, nan%, in area 185 
165
Male population: 0, nan%, female population: 0, nan%, in area 165 
151
Male population: 0, nan%, female population: 0, nan%, in area 151 
153
Male population: 0, nan%, female population: 0, nan%, in area 153 
157
Male population: 0, nan%, female population: 0, nan%, in area 157 
159
Male population: 0, nan%, female population: 0, nan%, in area 159 
161
Male population: 0, nan%, female population: 0, nan%, in area 161 
163
Male population: 0, nan%, female population: 0, nan%, in area 163 
167
Male population: 0, nan%, female popu

/tmp/ipykernel_57/3627287060.py:20: RuntimeWarning: invalid value encountered in ulong_scalars
  male_pct = (male_population/total_population) * 100
/tmp/ipykernel_57/3627287060.py:21: RuntimeWarning: invalid value encountered in ulong_scalars
  female_pct = (female_popultaion/total_population) * 100


In [44]:
sorted_dict = dict(sorted(male_pct_dict.items(), key=lambda item: item[1], reverse=True))
print(sorted_dict)

{' Region-Nordjylland': 50.505567840986366, ' Aalborg': 50.41119110374309, ' Esbjerg': 50.138736925029534, ' Region-Midtjylland': 50.03713192125288, ' Region-Syddanmark': 50.00499964052172, ' Region-Sjælland': 49.853303447127715, ' Hele-landet': 49.74934737912075, ' Odense': 49.51125446331696, ' Bornholm': 49.49680715197957, ' Aarhus': 49.127060264915976, ' Region-Hovedstaden': 49.083098029814195, ' Frederiksberg': 47.42871022589264, ' København': 0, ' Dragør': 0, ' Tårnby': 0, ' Albertslund': 0, ' Ballerup': 0, ' Brøndby': 0, ' Gentofte': 0, ' Gladsaxe': 0, ' Glostrup': 0, ' Herlev': 0, ' Hvidovre': 0, ' Høje-Taastrup': 0, ' Ishøj': 0, ' Lyngby-Taarbæk': 0, ' Rødovre': 0, ' Vallensbæk': 0, ' Allerød': 0, ' Egedal': 0, ' Fredensborg': 0, ' Frederikssund': 0, ' Furesø': 0, ' Gribskov': 0, ' Halsnæs': 0, ' Helsingør': 0, ' Hillerød': 0, ' Hørsholm': 0, ' Rudersdal': 0, ' Christiansø': 0, ' Greve': 0, ' Køge': 0, ' Lejre': 0, ' Roskilde': 0, ' Solrød': 0, ' Faxe': 0, ' Guldborgsund': 0, '

In [48]:
city_with_most_men_2020 = next(iter( sorted_dict.items()))
print(city_with_most_men_2020)

(' Region-Nordjylland', 50.505567840986366)


In [61]:
def sum_population(city_code, year):
    ld = loaded_data
    control = ld[np.isin(ld[:,0],[city_code])]
    population =  control[(control[:,3] == year)]
    total_population = population[:,4].sum()    
    print("Sum of population in year:"+str(year))
    return total_population

In [62]:
sum_population(751,2020)

Sum of population in year:2020


346072

In [64]:
def get_population_dict(city_list, year):
    population_list = {}
    for city_code, city_name in city_list.items():
        population_list[city_code] = sum_population(city_code, year)
    return population_list

In [65]:
population_list_2008 = get_population_dict(city_list, 2008)

Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of population in year:2008
Sum of p

In [67]:
population_list_2020 = get_population_dict(city_list, 2020)

Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of population in year:2020
Sum of p

In [84]:
sorted_pop_2008= dict(sorted(population_list_2008.items(), key=lambda item: item[1], reverse=True))

In [85]:
biggest_5_cities_2008= list(sorted_pop_2008.items())[1:6]
print("2008: ", biggest_5_cities_2008)

2008:  [(84, 1622110), (82, 1220089), (83, 1178469), (85, 807997), (81, 571367)]
