## Class exercise 1: table
![](images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation


In [ ]:
import numpy as np
a = np.arange(10, 30).reshape(4,5)
print(a)
yellow = a[0, 0]
red    = a[0, 1:4] 
blue   = a[0::2, 4] 
green  = a[0:3,2]
cyan = a[:,1::2]   
print('yellow:',yellow,'\nred:',red,'\ncyan:',cyan,'\nblue:',blue,'\ngreen:\n',green)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
yellow: 10 
red: [11 12 13] 
cyan: [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
blue: [14 24] 
green:
 [12 17 22]


Class exercise 2: cube

1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [76]:
a = np.arange(0, 27).reshape((3, 3, 3))
task1= a[1,1]
task2=a[0:3,1,0]
task3= a[0,:,2]

print(task1)
print(task2)
print(task3)

[12 13 14]
[ 3 12 21]
[2 5 8]


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6

In [5]:
data = np.arange(1,101).reshape(10,10)
a = data[data%2==0]
print(a)
b = data[np.where((data%10==6))]
print(b)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 6 16 26 36 46 56 66 76 86 96]


## class exercise: extracting
Based on the Copenhagen population data do the following (not including danish citizens):
1. Find the 10 largest population groups
2. Find the 10 largest population groups of children (0-17 y.o.) 
3. Create a barplot with the 10 largest groups on x-axis and 2 bars of both adult and children on y-axis
  - make one bar red and the other green
  - give them labels

Exercise numpy and csv
load the csv file: befkbhalderstatkode.csv into a numpy ndarray
How many german children of 0 years were there in Copenhagen in 2015?
create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
create a new function like previous so that it can sum values for all ages if age is not provided to the function
further add functionality to sum values if citizenship or area was not provided to function.
create a new function that can also give average values for each year if year whas not provided.
create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015
Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively
Find out what age most French people have in 2015

In [20]:
# read data from csv file into 2d numpy array
import numpy as np
filename = '../../../data/befkbhalderstatkode.csv'

bef_stats_df = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
dd = bef_stats_df

In [26]:

mask = (dd[:,0] == 2015) & (dd[:,2] == 0) & (dd[:,3] == 5180)
print(np.sum(dd[mask][:,4]))

[[2015    1    0 5180    3]
 [2015    2    0 5180    5]
 [2015    3    0 5180    7]
 [2015    4    0 5180    1]
 [2015    5    0 5180    1]
 [2015    6    0 5180    2]
 [2015    8    0 5180    2]
 [2015    9    0 5180    6]
 [2015   10    0 5180    8]]
35


In [31]:
def getPopulationData(AAR,BYDEL,ALDER,STATKODE):
    mask = (dd[:,0] == AAR) & (dd[:,1] == BYDEL) & (dd[:,2] == ALDER) & (dd[:,3] == STATKODE)
    return(dd[mask])
    

In [33]:
getPopulationData(2015,1,15,5100)

array([[2015,    1,   15, 5100,  367]], dtype=uint64)

In [48]:
def get_pop_adv(AAR,BYDEL,STATKODE,ALDER=None):
    year = dd[:,0] ==AAR
    city_part = dd[:,1] ==BYDEL
    state_code=dd[:,3] == STATKODE
    
    if ALDER !=None:
        age= dd[:,2] ==ALDER
        return dd[year & city_part & state_code & age]
    else:
        return np.sum(dd[year & city_part & state_code])
        
    

In [49]:
get_pop_adv(2015,1,5100,10)

array([[2015,    1,   10, 5100,  404]], dtype=uint64)